FROM sogis/qgis-server-base:3.4

# copy .qgs and .gpkg for dummy data
COPY qgis /data

#pg_service.conf File
COPY pg/pg_service.conf /etc/pg_service.conf
ENV PGSYSCONFDIR="/etc"

#sed command to change URL rewrite
RUN sed -i 's/\^\/qgis\//\^\/wms\//g' /etc/apache2/sites-enabled/qgis-server.conf
