FROM sogis/gretl-runtime:latest

WORKDIR /tmp

#TODO: add gradle scripts
COPY gradle/wait-for-it.sh /tmp/
COPY gradle/build.gradle /tmp/
COPY gradle/*.sql /tmp/
COPY gradle/avimport/*.sql /tmp/
COPY gradle/plzoimport/*.sql /tmp/
COPY gradle/gbkreisimport/*.sql /tmp/


USER 1001

ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/tmp/wait-for-it.sh db:5432 -- gretl -i"]
