version: '3.7'
services:
  qgis-server:
    image: "sogis/qgis-server-base:3.4"
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 2
      QGIS_FCGI_MAX_PROCESSES: 2
      QGIS_SERVER_LOG_LEVEL: 0
    volumes:
      - ./qgis:/data:ro
      #- ./postgresql-serviceconf:/etc/postgresql-common:ro
    ports:
      - 8083:80
