FROM sogis/oereb-wms:latest

# copy test files
COPY tests /tmp/tests

#test for http 200 status codes of GetCapabilities requests for both services
ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/tmp/tests/test-wms.sh"]
