FROM sogis/qgis-server-base:3.4

# copy .qgs and .gpkg for dummy data
COPY qgis /data

#pg_service.conf File
COPY pg/pg_service.conf /etc/postgresql-common/pg_service.conf
ENV PGSYSCONFDIR="/etc"

#sed command to change URL rewrite
RUN sed -i 's/\^\/qgis\//\^\/wms\//g' /etc/apache2/sites-enabled/qgis-server.conf

#tell apache/qgis-server where to find the pg_service.conf file
RUN echo 'SetEnv PGSYSCONFDIR "/etc/postgresql-common"' > /etc/apache2/mods-enabled/env.conf
