FROM sogis/gretl-runtime:latest

WORKDIR /tmp

#TODO: add gradle scripts
COPY gradle/xtfimport.sh /tmp/
COPY gradle/build.gradle /tmp/
COPY gradle/refresh_oereb-wms_materialized_views.sql /tmp/

USER 1001

ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/tmp/xtfimport.sh"]
