BEGIN;
-- schema stages
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_grundnutzung_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_sondernutzungsplaene_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_ueberlagernd_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_ueberlagernd_linie WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_ueberlagernd_punkt WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_nutzungsplanung_baulinien_linie WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_waldgrenzen_linie WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_weiteres_thema_einzelschutz_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW stage.vw_oerebwms_weiteres_thema_einzelschutz_punkt WITH DATA;
-- schema live
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_grundnutzung_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_sondernutzungsplaene_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_ueberlagernd_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_ueberlagernd_linie WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_ueberlagernd_punkt WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_nutzungsplanung_baulinien_linie WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_waldgrenzen_linie WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_weiteres_thema_einzelschutz_flaeche WITH DATA;
REFRESH MATERIALIZED VIEW live.vw_oerebwms_weiteres_thema_einzelschutz_punkt WITH DATA;
COMMIT;
