def appName = env.JOB_BASE_NAME
def environmentName = namespace.substring(namespace.lastIndexOf('-') + 1)

pipeline {
    agent any
    options {
        timeout(time: 120, unit: 'SECONDS')
    }
    stages {
        stage('Restart only') {
            when { expression { params.RESTART_ONLY } }
            steps {
                sh "oc rollout latest dc/${appName} -n ${namespace}"
                sh "oc rollout status dc/${appName} -n ${namespace}"
            }
        }
        stage('Deploy') {
            when { expression { !params.RESTART_ONLY } }
            steps {
                sh "oc process -f openshift/${appName}.yaml --param-file=openshift/${appName}_${environmentName}.params | oc apply -f - -n ${namespace}"
                sh "oc rollout status dc ${appName} -n ${namespace}"
            }
        }
    }
    post {
        always {
            sh "oc status --suggest -n ${namespace}"
        }
    }
}
